apiVersion: apps/v1
kind: Deployment
metadata:
  name: commondep
  labels:
    app: commonplacing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commonplacing
  template:
    metadata:
      name: commonplacing
      labels:
        app: commonplacing
    spec:
      containers:
      - name: commonplacing
        env:
        - name: STR1
          valueFrom:
            secretKeyRef:
              name: connstring
              key: connstring1
        - name: STR2
          valueFrom:
            secretKeyRef:
              name: connstring
              key: connstring2
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: mineql-mysql
              key: mysql-root-password
        image: localhost:5000/commonplacing:1.4
        ports:
          - containerPort: 8080
            name: http
        livenessProbe:
          httpGet:
            path: /
            port: http
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
#        image: qlek/commonplacing:1.2
