[development]
address = "localhost"
port = 8080
workers = 8
log = "normal"
limits = { forms = 32768 }

[production]
address = "localhost"
port = 8080
workers = 8
log = "normal"
limits = { forms = 32768 }
