[development]
address = "0.0.0.0"
port = 8080
workers = 8
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8080
workers = 8
log = "normal"
limits = { forms = 32768 }
